
import "./globals.css";
import Navbar from "@/componentes/Navbar";
import Footer from "@/componentes/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"

    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        <main className="mt-18">
          {children}
        </main>
        <Footer />
        </body>
    </html>
  );
}
